Open table methods
darrynten/pilot-live-php pull request #6
Opened 2017-08-17 13:09 UTC by fergusdixon

## Overview

| Q                 | A
| ----------------- | ---
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? | no
| Fixed issues      | #

## The problem
OpenTable was missing methods
...

## How I resolved it
Added them
...

## Questions
...

Notify the following people: @darrynten

2017-08-21 15:10 UTC, darrynten requested changes
Some minor change requests

2017-08-21 15:10 UTC, darrynten commented on README.md
> +  - [ ] Vendor Payment Collection
Oops I think this was me and my merge fix :/ sorry! Please correct :)

2017-08-21 15:10 UTC, darrynten commented on src/Models/Item.php
> +    protected $endpoint = '';
I think this can be removed from this model completely

2017-08-21 15:10 UTC, darrynten commented on src/Models/OpenTable.php
> +
Too many newlines

2017-08-21 15:10 UTC, darrynten commented on tests/PilotLive/Models/BaseModelTest.php
> -
Why all these removals?

2017-08-21 15:10 UTC, darrynten commented on tests/PilotLive/Models/OpenTableModelTest.php
> +    public function testDetail(){
Space between `()` and `{`

2017-08-21 15:10 UTC, darrynten commented on tests/PilotLive/Models/OpenTableModelTest.php
> +        ;
No semi colon on own line - the `]` from the line above should be here (and a trailing comma)

2017-08-22 07:57 UTC, fergusdixon commented on tests/PilotLive/Models/BaseModelTest.php
> -
I ran PHPStorm's code cleanup tool, must not like spaces between methods. Should I change it back?

2017-08-22 08:50 UTC, darrynten requested changes
Some minor change requests

2017-08-22 08:50 UTC, darrynten commented on tests/PilotLive/Models/BaseModelTest.php
> -
Yep, it's important to use newlines to group logic chunks of functionality in a method and make for lower cognitive load on developers when working on the code in the future.

Always remember that we write code for humans 😎

2017-08-22 08:50 UTC, darrynten commented on tests/PilotLive/Models/ItemModelTest.php
> +                'max' => 1000000,
Wondering if these should include (and require) the `.00`

2017-08-22 08:50 UTC, darrynten commented on tests/PilotLive/Models/OpenTableModelTest.php
> +            ];
Incorrect indentation

2017-08-22 09:58 UTC, darrynten commented on tests/PilotLive/Models/BaseModelTest.php
>          $model->{$key} = null;
I think the previous way with the 3 distinct segments, (1) we get the class, (2) we set expectations, (3) we so the thing, is the way to leave it.

Code must tell a story, and stories have paragraphs 😺

2017-08-22 09:59 UTC, darrynten commented on tests/PilotLive/Models/BaseModelTest.php
> -
This is an example of a good removal

2017-08-22 09:59 UTC, darrynten commented on tests/PilotLive/Models/BaseModelTest.php
> -
Good removal

2017-08-22 09:59 UTC, darrynten commented on tests/PilotLive/Models/BaseModelTest.php
> -
Not so good removal

2017-08-22 12:09 UTC, darrynten approved these changes
Looking good!

2017-08-22 12:22 UTC, merged